ДЗ 1
TiJon8/2024-2-VK-EDU-Frontend-T-Klimuk pull request #1
Opened 2024-09-27 14:36 UTC by TiJon8

# Домашнее задание № 1

Прошу @1MarBur1 проверить его.

Что было сделано:
* Добавлены тесты для функций convertBytesToHuman и nonUniqueElements
*
*

2024-09-28 21:47 UTC, 1MarBur1 requested changes

2024-09-28 21:47 UTC, 1MarBur1 commented on dz1/convertBytesToHuman.js
> +  }
Давай объеденим проверки типа данных в один if

Так же рассмотри случаи что будет если передать NaN, Infinity

2024-09-28 21:47 UTC, 1MarBur1 commented on dz1/convertBytesToHuman.js
> +  return `${rB.charAt(rB.length -1) === "0" ? rB.slice(0, -1) : rB} ${ext[index]}`;
зачем эта проверка? если я прокину 10240 - выведется 1 КБ, вместо ожидаемого 10 КБ

2024-09-28 21:47 UTC, 1MarBur1 commented on dz1/convertBytesToHuman.js
> +  const rB = parseFloat((bytes / Math.pow(kbToBytes, index)).toFixed(2)).toString()
здесь перевод в строку соответственно не нужен

parseFloat можно заменить на более очевидный "+" или Number()

2024-09-28 21:47 UTC, 1MarBur1 commented on dz1/convertBytesToHuman.test.js
> +  expect(convertBytesToHuman(null)).toBe(false)
пройдись по проекту и расставь точки с запятой

2024-09-28 21:47 UTC, 1MarBur1 commented on dz1/nonUniqueElements.js
> +  const duplicates = new Set();
Давай перепишем используя Map

Кажется не совсем понятным решением реализация через 2 Set()

2024-10-02 11:19 UTC, 1MarBur1 requested changes

2024-10-02 11:19 UTC, 1MarBur1 commented on dz1/nonUniqueElements.js
> +    };
давай перепишем это. 

```
col[item] ??= 0
col[item] += 1
```

сейчас если есть массив [1, 1, 1], то в col будет { 1: 2 }, хотя ожидаем { 1: 3 }

2024-10-02 11:19 UTC, 1MarBur1 commented on dz1/convertBytesToHuman.js
> +    'Bytes',
почему решил переименовать? давай вернем B?

2024-10-02 11:19 UTC, 1MarBur1 commented on dz1/convertBytesToHuman.js
> +  // }
можно убрать

2024-10-03 12:28 UTC, 1MarBur1 approved these changes
@HaseProgram @martinkomitsky @kgrechin approved

2024-10-04 19:21 UTC, merged

2024-10-04 19:21 UTC, martinkomitsky commented
12!